Description:
    Udacity Course 2 IAM Role for S3 buckets access, Peter Predtechensky

Resources:

    S3AccessRole:
        Type: "AWS::IAM::Role"
        Properties: 
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                -   Effect: "Allow"
                    Principal: 
                        Service: 
                        - "ec2.amazonaws.com"
                    Action: 
                    - "sts:AssumeRole"
            Path: "/"
            Policies:
            -   PolicyName: "root"
                PolicyDocument: 
                    Version: "2012-10-17"
                    Statement: 
                    -   Effect: "Allow"
                        Action: "*"
                        Resource: "*"

    RootInstanceProfile:
        Type: "AWS::IAM::InstanceProfile"
        Properties:
            Path: "/"
            Roles:
            -   Ref: "S3AccessRole"