Description:
    Udacity Course 2 RDS instance creation, Peter Predtechensky

Resources:

    Course2RDS:
        Type: AWS::RDS::DBInstance
        Properties: 
          AllocatedStorage: 10
          DBInstanceClass: db.t2.micro
          DBInstanceIdentifier: course2testrds
          DBName: pedro
          DBSubnetGroupName: oregon-subnet-group
          Engine: MySQL
          MasterUsername: admin
          MasterUserPassword: Huawei#12
          MultiAZ: false
          PubliclyAccessible: false
          VPCSecurityGroups: 
          - sg-0b6a9513d71514882
